### ISSUE TITLE
Unable to connect to google home

### ISSUE THREAD

**Issue by rtmlp** [benov84/homebridge-chromecast-speaker#2]
Hi,

I have couple of Google Home's, one Google home mini and one Google TV at my home. However I am not able to connect to them

I added the following lines to the `config.json` 

```
"platforms":[
    {
      "platform": "ChromecastSpeaker",
      "name": "ChromecastSpeaker"
    }
]

```

I got the following errors after I restart the homebridge

```
[ChromecastSpeaker] Initializing ChromecastSpeaker platform...
Error: dns service error: unknown
    at new Browser (/homebridge/node_modules/homebridge-chromecast-speaker/node_modules/mdns/lib/browser.js:88:10)
    at Object.create [as createBrowser] (/homebridge/node_modules/homebridge-chromecast-speaker/node_modules/mdns/lib/browser.js:116:10)
    at new ControlChromecastSpeakerPlatform (/homebridge/node_modules/homebridge-chromecast-speaker/index.js:43:29)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
Got SIGTERM, shutting down Homebridge...
```
Can you let me know what I am doing wrong here

Thanks

**Comment by rtmlp** [comment]
I also noticed the following message in the log

```
The plugin "homebridge-chromecast-speaker" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin
```

**Comment by Ciuffi** [comment]
Having the same issue, any updates on this? I'm running homebridge in Docker if that matters.

**Comment by benov84** [comment]
This is related with installing mdns library, a prerequisite to this repository.

https://github.com/agnat/node_mdns

Try to install the library itself using the instructions and file an issue there, please.
